name: Construir y lanzar para Windows y macOS

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v3

            - name: Configurar Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.13.3'

            - name: Instalar dependencias
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Construir ejecutable de Windows
              run: pyinstaller --onefile --windowed app/main.py

            - name: Subir binario de Windows
              uses: softprops/action-gh-release@v1
              with:
                  files: dist/*.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v3

            - name: Configurar Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.13.3'

            - name: Instalar dependencias
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Construir ejecutable de macOS
              run: pyinstaller --onefile --windowed app/main.py

            - name: Campactar binario de macOS
              uses: softprops/action-gh-release@v1
              with:
                  files: dist/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
